services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    env_file: ".env"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    command: uvicorn lucid_docs.main:create_app --host 0.0.0.0 --port 8000 --reload
