services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
      - chroma_db:/app/chroma_db
    ports:
      - "8000:8000"
    env_file: ".env"
    environment:
      - ENVIRONMENT=dsv
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    entrypoint: /app/entrypoint.sh
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: lucid_docs
      #MONGO_INITDB_ROOT_USERNAME: lucid_docs
      #MONGO_INITDB_ROOT_PASSWORD: Lucid2025
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  chroma_db:
