FROM python:3.10-slim

WORKDIR /app

# Instalar dependências do sistema
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Instalar Poetry
ENV POETRY_VERSION=2.1.3
RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"

# Configurar Poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV PATH="/app/.venv/bin:$PATH"

# Copiar estrutura do projeto primeiro
COPY pyproject.toml poetry.lock ./
COPY src /app/src

# Instalar dependências
RUN poetry install --no-interaction --no-ansi --no-root

# Copiar o entrypoint
COPY entrypoint.sh /app/entrypoint.sh

# Instalar pytest
RUN poetry add --dev pytest

# Copiar o restante
COPY tests /app/tests

EXPOSE 8000

CMD ["uvicorn", "lucid_docs.main:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]